name: Test Filecoin FVM Localnet Docker Images

on:
  workflow_dispatch:
    {}

env:
  REGISTRY: ghcr.io
  NAMESPACE: ${{ github.repository_owner }}
  IMAGE_NAME: filecoin-fvm-localnet
  ADDRESS: t410fuir2myuqqjlacl3o3dyw362mx4iftiav3kkb4ja
  PRIVATE_KEY: afea7f0655db527a92e2d4b4121f340f58dee4f44fe2ea67fcfdfa723f786a45

jobs:
  test-filecoin:
    name: Test Filecoin
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
    outputs:
      digest: ${{ steps.build.outputs.digest }}

    steps:
      - name: Set up node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.15

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Checkout localnet
        uses: actions/checkout@v3
        with:
          path: localnet

      - name: Checkout FEVM starter kit
        uses: actions/checkout@v3
        with:
          repository: filecoin-project/fevm-hardhat-kit
          path: fevm-hardhat-kit
          
      - name: Start localnet
        uses: isbang/compose-action@v1.4.1
        with: 
          compose-file: "./localnet/docker-compose.yaml"
          
      - name: Fund local wallet
        run: |
          cd localnet
          docker compose exec lotus lotus send ${{ env.ADDRESS }} 888
          sleep 45
          docker compose exec lotus lotus wallet balance ${{ env.ADDRESS }}
          
      - name: Deploy contracts
        run: |
          cd fevm-hardhat-kit
          yarn install
          yarn hardhat deploy --reset --network localnet
          sleep 45
          
      - name: Execute Deal Client contract
        run: |
          cd fevm-hardhat-kit
          export DEAL_CLIENT_ADDRESS=`jq -r .address deployments/localnet/DealClient.json`
          yarn hardhat make-deal-proposal \
            --network localnet \
            --contract $DEAL_CLIENT_ADDRESS \
            --piece-cid baga6ea4seaqaurso3nekgbu4ujngn4toexboyetcbdo5e2pu6rdymbu2gxpz4hi \
            --piece-size 256 \
            --verified-deal false \
            --label bafybeiamxozxs25gtpfrpbmr7w44ylafvufp6aximtkwx5ecqozpdfcohi \
            --start-epoch 100000 \
            --end-epoch 1000000 \
            --storage-price-per-epoch 0 \
            --provider-collateral 0 \
            --client-collateral 0 \
            --extra-params-version 1 \
            --location-ref "https://data-depot.lighthouse.storage/api/download/download_car?fileId=6aa1b4e8-6a2d-4cda-90c6-b36c620c1c05.car" \
            --car-size 216 \
            --skip-ipni-announce false \
            --remove-unsealed-copy false 
          sleep 45
          
        

